# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('WR', 'Wide Reciever'), ('CB', 'Cornerback'), ('K', 'Kicker'), ('P', 'Punter'), ('LS', 'Long Snapper')], max_length=3)),
                ('college', models.CharField(max_length=100)),
                ('data_json', models.TextField()),
            ],
        ),
    ]
