# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftcardposter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.CharField(max_length=100)),
                ('range_def', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
