# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftcardposter', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='subreddit',
            field=models.CharField(default='test', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('WR', 'Wide Reciever'), ('CB', 'Cornerback'), ('K', 'Kicker'), ('P', 'Punter'), ('LS', 'Long Snapper'), ('DE', 'Defensive End'), ('ILB', 'Inside Linebacker'), ('DT', 'Defensive Tackle'), ('RB', 'Runningback'), ('OT', 'Offensive Tackle'), ('OG', 'Offensive Guard'), ('TE', 'Tight end'), ('S', 'Safety'), ('LB', 'Linebacker'), ('C', 'Center'), ('FB', 'Fullback'), ('DB', 'Defensive Back'), ('OLB', 'Outside Linebacker'), ('OL', 'Offensive Lineman'), ('SS', 'Strong Safety'), ('DL', 'Defensive Lineman'), ('NT', 'Nose Tackle'), ('FS', 'Free Safety')], max_length=3),
        ),
    ]
