# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftcardposter', '0005_auto_20170427_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='live_thread_id',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
