# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftcardposter', '0007_auto_20170429_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='prio5',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priority',
            name='prio6',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
