# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftcardposter', '0009_auto_20170625_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='layout',
            field=models.CharField(default='card-layout.html', max_length=100),
        ),
    ]
