# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftcardposter', '0010_settings_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='last_submitted_overall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('WR', 'Wide Reciever'), ('CB', 'Cornerback'), ('K', 'Kicker'), ('P', 'Punter'), ('LS', 'Long Snapper'), ('DE', 'Defensive End'), ('ILB', 'Inside Linebacker'), ('DT', 'Defensive Tackle'), ('RB', 'Runningback'), ('OT', 'Offensive Tackle'), ('OG', 'Offensive Guard'), ('TE', 'Tight end'), ('S', 'Safety'), ('LB', 'Linebacker'), ('C', 'Center'), ('FB', 'Fullback'), ('DB', 'Defensive Back'), ('OLB', 'Outside Linebacker'), ('OL', 'Offensive Lineman'), ('SS', 'Strong Safety'), ('DL', 'Defensive Lineman'), ('NT', 'Nose Tackle'), ('FS', 'Free Safety'), ('BL', 'Bandleader'), ('4-3 DT', '4-3 Defensive Tackle'), ('4-3 DE', '4-3 Defensive End'), ('4-3 MLB', '4-3 Middle Linebacker'), ('4-3 OLB', '4-3 Outside Linebacker'), ('3-4 DT', '3-4 Defensive Tackle'), ('3-4 DE', '3-4 Defensive End'), ('3-4 ILB', '3-4 Inside Linebacker'), ('3-4 OLB', '3-4 Outside Linebacker')], max_length=3),
        ),
        migrations.AlterField(
            model_name='priority',
            name='position',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('WR', 'Wide Reciever'), ('CB', 'Cornerback'), ('K', 'Kicker'), ('P', 'Punter'), ('LS', 'Long Snapper'), ('DE', 'Defensive End'), ('ILB', 'Inside Linebacker'), ('DT', 'Defensive Tackle'), ('RB', 'Runningback'), ('OT', 'Offensive Tackle'), ('OG', 'Offensive Guard'), ('TE', 'Tight end'), ('S', 'Safety'), ('LB', 'Linebacker'), ('C', 'Center'), ('FB', 'Fullback'), ('DB', 'Defensive Back'), ('OLB', 'Outside Linebacker'), ('OL', 'Offensive Lineman'), ('SS', 'Strong Safety'), ('DL', 'Defensive Lineman'), ('NT', 'Nose Tackle'), ('FS', 'Free Safety'), ('BL', 'Bandleader'), ('4-3 DT', '4-3 Defensive Tackle'), ('4-3 DE', '4-3 Defensive End'), ('4-3 MLB', '4-3 Middle Linebacker'), ('4-3 OLB', '4-3 Outside Linebacker'), ('3-4 DT', '3-4 Defensive Tackle'), ('3-4 DE', '3-4 Defensive End'), ('3-4 ILB', '3-4 Inside Linebacker'), ('3-4 OLB', '3-4 Outside Linebacker')], max_length=3),
        ),
    ]
